/*
 * STEPPER_config.h
 *
 *  Created on: Oct 14, 2023
 *      Author: hp
 */

#ifndef MINE_HAL_STEPPER_MOTOR_STEPPER_CONFIG_H_
#define MINE_HAL_STEPPER_MOTOR_STEPPER_CONFIG_H_

#define STEPPER_PORT   DIO_PORTA

#define STEPPER_BLUE_PIN     DIO_PIN0
#define STEPPER_PINK_PIN     DIO_PIN1
#define STEPPER_YELLOW_PIN   DIO_PIN2
#define STEPPER_ORANGE_PIN   DIO_PIN3


#endif /* MINE_HAL_STEPPER_MOTOR_STEPPER_CONFIG_H_ */
